import express from "express";
import { createEducation,updateEducation ,getEducationDetails,getByFilter, deleteEducation} from "../controllers/Education.controller.js";
import protectRoute from "../middleware/protectRoute.js";
const router = express.Router();
router.post("/",protectRoute, createEducation);
router.get("/",protectRoute, getEducationDetails);
router.delete("/:id", protectRoute,deleteEducation);
router.patch("/:id", protectRoute,updateEducation);
router.get("/filter",protectRoute, getByFilter);
router.get("/all",protectRoute, getByFilter);
export default router;
